### PR TITLE
Install unversioned lib symlink

### PR DESCRIPTION
**Pull request by pudiva**
https://github.com/void-linux/void-packages/pull/29627#issuecomment-804182904

### CODE REVIEW

**Comment by alexpevzner** [comment]
Hi @pudiva 

It will break "normal" behaviour of `make install`. In particular, it will break `make install` used by packaging.

If you wish, you may add additional target (say, `make symlink`) which installs only symlink, bypassing all another installation steps.

**Comment by pudiva** [comment]
Hi @alexpevzner. I'm doing the packaging for void-linux, and @ericonr noted that `make install` isn't providing the unversioned symlink and suggested to report. I may be wrong, but it does feel strange to me.

So you say we should do the symlink on our end instead?

**Comment by alexpevzner** [comment]
OK, I understood, sorry.

sane-airscan really doesn't create unversioned symlink, but seems that nobody actually need this link. Everything works just fine without it.

**Comment by pudiva** [comment]
> sane-airscan really doesn't create unversioned symlink, but seems that nobody actually need this link. Everything works just fine without it.

Indeed sane can `dlopen()` the driver and it works.

Now I suppose not many people will try to link against this `.so` as it's a sane backend, or whether it's important for `dlopen()` in the case multiple versions are available, or if there's any other use for this link...

but other backends do include the unversioned symlink, so :woman_shrugging:

**Comment by pudiva** [comment]
Also it seems that building with **meson** does generate the symlink, while building with **make** doesn't.

**Comment by alexpevzner** [comment]
Nobody links against these drivers directly, they are always loaded via `sane-dll`, which doesn't use unversioned symlink. So I believe that SANE itself creates these links only for legacy reasons and there is no need to reproduce this behaviour in the independent package.

Official packages for Fedora, Debian and Ubuntu come without this symlink and it causes no problems and no complains.

Regarding meson build, it was contributed by my users and I don't maintain it, I only keep it here for everybody's convenience and trying not to break when something changes in the project.

So really thank for your contribution, but in this particular case I don't think we really need it.

**Comment by pudiva** [comment]
Okay! :sparkles: :sparkles: :sparkles:

**Comment by alexpevzner** [comment]
So I guess we can probably close this PR now?

**Pull request closed without merging**
